linters:
  enable-all: true
  disable:
    - dupl
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - lll
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - musttag
    - depguard

    #
    # Maybe fix later:
    #
    - cyclop
    - gocognit
    - goconst
    - gosec
    - ireturn
    - noctx
    - tagliatelle
    - perfsprint

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - copyloopvar

    #
    # Disabled due to versioning:
    #
    - intrange
    - exportloopref


linters-settings:
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

output:
  print-issued-lines: true
  sort-results: true
