# https://goreleaser.com/customization/builds/
project_name: mev-boost
builds:
  - id: mev-boost
    tags:
      - osusergo
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -extldflags=-static
      - -w -s
      - -X github.com/flashbots/mev-boost/config.Version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    # Default is empty.
    ignore:
      - goos: windows
        goarch: arm64

    # Overrides allows to override some fields for specific targets.
    # This can be specially useful when using CGO.
    # Note: it'll only match if the full target matches.
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
      - goos: windows
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc