project_name: mev-boost
builds:
  - id: mev-boost
    flags:
      - -trimpath
    ldflags:
      - -w -s
      - -X github.com/flashbots/mev-boost/config.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64